### Add Flight
POST http://localhost:4004/odata/v2/flightSet/Flights
Content-Type: application/json

{ "carrID":"AA", 
  "connID":"0123",
  "fldate":"2022-03-30T12:00:00Z"
}

### Get All Flights
GET http://localhost:4004/flightSet/Flights

### Get A single flight
GET http://localhost:4004/odata/v2/flightSet/Flights(carrID='DL',connID='1984',fldate=datetimeoffset'2022-05-31T22:00:00Z')